
import { ClockConfig } from '../../types';

export const SEED_CLOCKS: ClockConfig[] = [
{
  "id": "default_clock",
  "name": "Standard Tournament Clock",
  "description": "Premium layout with high visibility and room for branding.",
  "backgroundColor": "#5b1a08",
  "fontColor": "#FFFFFF",
  "isDefault": true,
  "fields": [
    {
      "id": "6087bcb8-e196-441d-b52d-60d688fa831f",
      "type": "shape_rect",
      "label": "shape_rect",
      "x": 50,
      "y": 10,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#64250f",
      "align": "center",
      "showLabel": false,
      "width": 1300,
      "height": 100,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "d7668191-096a-4c3d-a048-7d0a07cfddb7",
      "type": "shape_rect",
      "label": "shape_rect",
      "x": 15,
      "y": 42.84547827792784,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#64250f",
      "align": "center",
      "showLabel": false,
      "width": 300,
      "height": 300,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "f38857e5-4d32-4430-9d3b-55c03ad81ac7",
      "type": "shape_rect",
      "label": "shape_rect",
      "x": 15,
      "y": 77.5,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#64250f",
      "align": "center",
      "showLabel": false,
      "width": 300,
      "height": 100,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "edc3ad98-5ae8-4de4-a7a3-33e3f65d13c5",
      "type": "shape_rect",
      "label": "shape_rect",
      "x": 50,
      "y": 95,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#64250f",
      "align": "center",
      "showLabel": false,
      "width": 1300,
      "height": 100,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "86c9d61a-c109-44a6-bfee-0560921a71b3",
      "type": "shape_rect",
      "label": "shape_rect",
      "x": 85,
      "y": 30,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#64250f",
      "align": "center",
      "showLabel": false,
      "width": 300,
      "height": 125,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "aa99ea85-2eb5-4f5d-a167-a799494967fe",
      "type": "shape_rect",
      "label": "shape_rect",
      "x": 85,
      "y": 52.65452172207216,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#64250f",
      "align": "center",
      "showLabel": false,
      "width": 300,
      "height": 125,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "7897b67f-e34f-4b68-87b3-de9e1a1dede4",
      "type": "shape_rect",
      "label": "shape_rect",
      "x": 85,
      "y": 75,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#64250f",
      "align": "center",
      "showLabel": false,
      "width": 300,
      "height": 125,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "d849a6f6-3c01-489e-96bb-f6090056de43",
      "type": "blind_countdown",
      "label": "blind_countdown",
      "x": 50,
      "y": 37.47234755315457,
      "fontSize": 150,
      "fontWeight": "bold",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "e85dc5a1-dbfb-45a9-9b2d-9e8f5207252a",
      "type": "blind_level",
      "label": "blind_level",
      "x": 42.5,
      "y": 65,
      "fontSize": 32,
      "fontWeight": "bold",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "labelText": "BLINDS",
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "77ef9bed-786e-4061-a21e-89433522853a",
      "type": "ante",
      "label": "ante",
      "x": 62.5,
      "y": 65,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "labelText": "ANTE",
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "0de32d3c-f4a1-4e1b-8ca3-4c2efbabe377",
      "type": "line",
      "label": "line",
      "x": 50,
      "y": 72.40564970046326,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#bf8d69",
      "align": "center",
      "showLabel": false,
      "width": 450,
      "height": 4,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "184fc970-9f40-483a-a024-7119c5709b90",
      "type": "next_blinds",
      "label": "next_blinds",
      "x": 42.5,
      "y": 80,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#5e5a5a",
      "align": "center",
      "showLabel": true,
      "labelText": "NEXT BLINDS",
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "5eeda6e2-b2ce-4eb1-aec0-cb7f61d5c52d",
      "type": "next_ante",
      "label": "next_ante",
      "x": 62.5,
      "y": 80,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#5f4743",
      "align": "center",
      "showLabel": true,
      "labelText": "NEXT ANTE",
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "d6816d95-657f-45d6-9b81-64a7cf4b4587",
      "type": "avg_stack",
      "label": "avg_stack",
      "x": 85,
      "y": 52.935912719371046,
      "fontSize": 50,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "labelText": "",
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "bedf0aaf-c642-400b-8fcc-7d1d1c41a74f",
      "type": "tournament_name",
      "label": "tournament_name",
      "x": 50,
      "y": 10,
      "fontSize": 80,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "5a566683-6220-45fc-890d-6af2a5525f07",
      "type": "custom_text",
      "label": "custom_text",
      "x": 15,
      "y": 10,
      "fontSize": 50,
      "fontWeight": "normal",
      "color": "#c08d6a",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0,
      "customText": "6BET"
    },
    {
      "id": "58a5736b-ff7e-437e-bf27-3b21b1cd9776",
      "type": "rebuy_limit",
      "label": "rebuy_limit",
      "x": 15,
      "y": 47.99121761306191,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "labelText": "",
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "8ff819e1-0a42-4261-a38e-f46cc3a42b56",
      "type": "est_end_time",
      "label": "est_end_time",
      "x": 15,
      "y": 35,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "labelText": "EST END",
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "62ecec6d-216e-4bc1-8b6a-b09c5ca28596",
      "type": "payout_total",
      "label": "payout_total",
      "x": 15,
      "y": 77.5,
      "fontSize": 50,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "5b11f89a-847b-4699-b43a-7ac1d5f5feab",
      "type": "next_break",
      "label": "next_break",
      "x": 84.91308259699694,
      "y": 30.336695890989755,
      "fontSize": 50,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "869902eb-b884-4882-8850-8d52f8f09775",
      "type": "players_count",
      "label": "players_count",
      "x": 85,
      "y": 75,
      "fontSize": 50,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0
    },
    {
      "id": "4ad9090c-00fd-40d4-8c05-23cd49ca5266",
      "type": "image",
      "label": "image",
      "x": 85.37538302224712,
      "y": 10.287917427454754,
      "fontSize": 32,
      "fontWeight": "normal",
      "color": "#FFFFFF",
      "align": "center",
      "showLabel": false,
      "width": 70,
      "height": 70,
      "borderColor": "#ffffff",
      "borderWidth": 0,
      "imageUrl": "https://cdn-next.cybassets.com/media/W1siZiIsIjIzMjY4L2F0dGFjaGVkX3Bob3Rvcy8xNzA0NDE5NDY3X09H5ZyWLnBuZy5wbmciXV0.png?sha=f51c44ce228198e2"
    },
    {
      "id": "1f90dd64-a764-4897-b780-302ad00684dd",
      "type": "custom_text",
      "label": "custom_text",
      "x": 93.11103188951984,
      "y": 23.422263803588404,
      "fontSize": 20,
      "fontWeight": "normal",
      "color": "#c08d6a",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0,
      "customText": "Next Break"
    },
    {
      "id": "e6b791fe-7c73-49f9-9101-09d572c8e9b8",
      "type": "custom_text",
      "label": "custom_text",
      "x": 93.19884902345242,
      "y": 45.973652839185746,
      "fontSize": 20,
      "fontWeight": "normal",
      "color": "#c08d6a",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0,
      "customText": "Avg Stack"
    },
    {
      "id": "ccd2f2df-0877-435c-b42a-0df0ea1b9b96",
      "type": "custom_text",
      "label": "custom_text",
      "x": 93.28666615738501,
      "y": 68.37052015271092,
      "fontSize": 20,
      "fontWeight": "normal",
      "color": "#c08d6a",
      "align": "center",
      "showLabel": true,
      "borderColor": "#ffffff",
      "borderWidth": 0,
      "customText": "Players"
    },
    {
      "id": "0bc7d5a3-6f68-41c8-be8c-04be9a4a55d3",
      "type": "custom_text",
      "label": "custom_text",
      "x": 50,
      "y": 93.65452172207216,
      "fontSize": 25,
      "fontWeight": "bold",
      "color": "#c08d6a",
      "align": "center",
      "showLabel": true,
      "width": 1100,
      "borderColor": "#ffffff",
      "borderWidth": 0,
      "isTicker": true,
      "customText": "這是跑馬燈～      這是跑馬燈～      這是跑馬燈～",
      "fontStyle": "italic",
      "textDecoration": "none"
    }
  ]
},
    {
        "id": "clock_light",
        "name": "Light Theme (Modern)",
        "description": "Clean white background with dark text. Good for brightly lit rooms.",
        "backgroundColor": "#E6E6E6",
        "fontColor": "#111111",
        "isDefault": false,
        "fields": [
            {
            "id": "lt_6087bcb8",
            "type": "shape_rect",
            "label": "shape_rect",
            "x": 50,
            "y": 10,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#FFFFFF",
            "align": "center",
            "showLabel": false,
            "width": 1300,
            "height": 100,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_d7668191",
            "type": "shape_rect",
            "label": "shape_rect",
            "x": 15,
            "y": 42.84547827792784,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#FFFFFF",
            "align": "center",
            "showLabel": false,
            "width": 300,
            "height": 300,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_f38857e5",
            "type": "shape_rect",
            "label": "shape_rect",
            "x": 15,
            "y": 77.5,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#FFFFFF",
            "align": "center",
            "showLabel": false,
            "width": 300,
            "height": 100,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_edc3ad98",
            "type": "shape_rect",
            "label": "shape_rect",
            "x": 50,
            "y": 95,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#FFFFFF",
            "align": "center",
            "showLabel": false,
            "width": 1300,
            "height": 100,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_86c9d61a",
            "type": "shape_rect",
            "label": "shape_rect",
            "x": 85,
            "y": 30,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#FFFFFF",
            "align": "center",
            "showLabel": false,
            "width": 300,
            "height": 125,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_aa99ea85",
            "type": "shape_rect",
            "label": "shape_rect",
            "x": 85,
            "y": 52.5,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#FFFFFF",
            "align": "center",
            "showLabel": false,
            "width": 300,
            "height": 125,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_7897b67f",
            "type": "shape_rect",
            "label": "shape_rect",
            "x": 85,
            "y": 75,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#FFFFFF",
            "align": "center",
            "showLabel": false,
            "width": 300,
            "height": 125,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_d849a6f6",
            "type": "blind_countdown",
            "label": "blind_countdown",
            "x": 50,
            "y": 37.47234755315457,
            "fontSize": 150,
            "fontWeight": "bold",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_e85dc5a1",
            "type": "blind_level",
            "label": "blind_level",
            "x": 42.5,
            "y": 65,
            "fontSize": 32,
            "fontWeight": "bold",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "labelText": "BLINDS",
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_77ef9bed",
            "type": "ante",
            "label": "ante",
            "x": 62.5,
            "y": 65,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "labelText": "ANTE",
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_0de32d3c",
            "type": "line",
            "label": "line",
            "x": 50,
            "y": 72.40564970046326,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#999999",
            "align": "center",
            "showLabel": false,
            "width": 450,
            "height": 4,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_184fc970",
            "type": "next_blinds",
            "label": "next_blinds",
            "x": 42.5,
            "y": 80,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "labelText": "NEXT BLINDS",
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_5eeda6e2",
            "type": "next_ante",
            "label": "next_ante",
            "x": 62.5,
            "y": 80,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "labelText": "NEXT ANTE",
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_d6816d95",
            "type": "avg_stack",
            "label": "avg_stack",
            "x": 85,
            "y": 52.935912719371046,
            "fontSize": 50,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "labelText": "",
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_bedf0aaf",
            "type": "tournament_name",
            "label": "tournament_name",
            "x": 50,
            "y": 10,
            "fontSize": 80,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_5a566683",
            "type": "custom_text",
            "label": "custom_text",
            "x": 15,
            "y": 10,
            "fontSize": 50,
            "fontWeight": "normal",
            "color": "#333333",
            "align": "center",
            "showLabel": true,
            "borderColor": "#ffffff",
            "borderWidth": 0,
            "customText": "6BET"
            },
            {
            "id": "lt_58a5736b",
            "type": "rebuy_limit",
            "label": "rebuy_limit",
            "x": 15,
            "y": 47.99121761306191,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "labelText": "",
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_8ff819e1",
            "type": "est_end_time",
            "label": "est_end_time",
            "x": 15,
            "y": 35,
            "fontSize": 32,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "labelText": "EST END",
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_62ecec6d",
            "type": "payout_total",
            "label": "payout_total",
            "x": 15,
            "y": 77.5,
            "fontSize": 50,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_5b11f89a",
            "type": "next_break",
            "label": "next_break",
            "x": 85,
            "y": 30,
            "fontSize": 50,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "borderColor": "#ffffff",
            "borderWidth": 0
            },
            {
            "id": "lt_869902eb",
            "type": "players_count",
            "label": "players_count",
            "x": 85,
            "y": 75,
            "fontSize": 50,
            "fontWeight": "normal",
            "color": "#111111",
            "align": "center",
            "showLabel": true,
            "borderColor": "#ffffff",
            "borderWidth": 0
            }
        ]
    }
];
